#!/bin/bash
#Copyright (c) 2026, Michael McFadden
#GNU GENERAL PUBLIC LICENSE Version 2
#See file LICENCE or visit https://github.com/flipmcf/CasterPak/blob/master/LICENSE
# setup.sh - CasterPak Configuration Wizard

if [ -f .env ]; then
    read -p ".env already exists. Overwrite? (y/n) " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        exit 1
    fi
fi

echo "--- CasterPak Setup Wizard ---"

# 1. Input Type

read -p "Input Type [filesystem, http, ftp, scp, rsync] (default: filesystem): " input_type

input_type=${input_type:-filesystem}



if [ "$input_type" == "filesystem" ]; then

    read -p "Local path to videos (default: ~/Videos): " video_path

    video_path=${video_path:-~/Videos}

fi

# See docs/Hosting-instructions - this is the one Cache Volume, mounted
# whole; video_input/ and segments/ are sub-directories CasterPak manages
# under it, not separate mounts.
read -p "Host directory for the CasterPak cache volume (default: /var/cache/casterpak): " host_cache_path

host_cache_path=${host_cache_path:-/var/cache/casterpak}


# 2. Cache Input t/f

read -p "Cache/copy input video files from library? (y/n, default: n): " cache_input

if [[ $cache_input =~ ^[Yy]$ ]]; then cache_input="True"; else cache_input="False"; fi

# 3. Server Name

read -p "Server Name for manifests (default: localhost): " servername

servername=${servername:-localhost}



# Write to .env

cat <<EOF > .env

CASTERPAK_INPUT_INPUT_TYPE=$input_type

CASTERPAK_FILESYSTEM_CACHE_INPUT=$cache_input

CASTERPAK_OUTPUT_SERVERNAME=$servername

HOST_VIDEO_PATH=$video_path

HOST_CACHE_PATH=$host_cache_path

APP_PORT=5000

EOF



echo "Done! You can now run 'docker compose up -d'"
