#don't edit this file unless it's production config.  It will end up in the build.
# see 'config_overrides' for development config changes

server {
    listen 80;
    location / {
        proxy_pass http://casterpak:5000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;

        include /etc/nginx/config_overrides/*.conf;
        
    }
    
    location /protected_media/ {
        # 'internal' means the outside internet gets a 404 if they try to access this path directly.
        # It can ONLY be triggered by Flask sending the X-Accel-Redirect header.
        internal;
        
        # This points to the actual disk mount point inside the Nginx container that it shares with casterpak (flask)
        alias /tmp/segments/;
        
        # Performance tuning for video delivery
        sendfile on;
        tcp_nopush on;
        tcp_nodelay on;

        # Ensure proper MIME type is served if Flask doesn't set it
        default_type video/MP2T;
        
        # CORS Headers: Required if the js video player is on a different domain
        add_header Access-Control-Allow-Origin *;
    }

    location /testing/ {
        alias /etc/nginx/html/testing/; 
        index test_player.html;
    }

    # Video Streaming Optimization
    proxy_buffering off;
    proxy_request_buffering off;
}
